name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el workflow diariamente
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AndresDz2024

      - name: Push to repository
        run: |
          git add dist/github-snake.svg
          git commit -m "Updated snake animation"
          git push
